packages:
  - "."

allowBuilds:
  '@firebase/util': set this to true or false
  bufferutil: set this to true or false
  esbuild: true
  msgpackr-extract: true
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
