import type { CatalogProduct } from "../types";

export const corporateWebsite: CatalogProduct = {
  id: "web-corp-001",
  name: "Firemná webová stránka",
  slug: "firemna-webova-stranka",
  category: "web-development",
  featured: true,
  shortDescription:
    "Profesionálna firemná webová stránka s moderným dizajnom a SEO optimalizáciou",
  features: [
    "Moderný a responzívny dizajn",
    "Bleskovo rýchly loading (LCP < 2.5s)",
    "SEO optimalizácia a Google Rankings",
    "Odporúčaná kombinácia s mesačnými SEO balíkmi",
    "Mobile-first prístup",
    "Tmavý/svetlý režim",
    "Integrácia Google Analytics 4",
    "SSL certifikát a GDPR compliant",
    "Kontaktný formulár s validáciou",
    "Google Maps integrácia",
    "CMS pre ľahkú správu obsahu",
  ],
  pricing: [
    {
      id: "basic",
      name: "Základný balík",
      price: 1500,
      currency: "EUR",
      billingPeriod: "one-time",
      description: "Perfektné pre malé podniky",
      features: [
        "Do 5 podstránok",
        "Responzívny dizajn",
        "Základné SEO",
        "Kontaktný formulár",
        "3 revízie dizajnu",
        "3 mesiace podpory",
      ],
    },
    {
      id: "professional",
      name: "Profesionálny balík",
      price: 2500,
      currency: "EUR",
      billingPeriod: "one-time",
      isPopular: true,
      description: "Najpopulárnejší balík",
      features: [
        "Do 10 podstránok",
        "Blog systém",
        "Pokročilá SEO",
        "Multi-jazyčnosť (2 jazyky)",
        "Newsletter integrácia",
        "5 revízií dizajnu",
        "Animácie a interakcie",
        "6 mesiacov podpory",
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise Riešenie",
      price: 4500,
      currency: "EUR",
      billingPeriod: "one-time",
      description: "Úplné riešenie pre väčšie firmy",
      features: [
        "Neomedzený počet stránok",
        "Vlastný CMS systém",
        "API integrácie",
        "Admin dashboard",
        "Pokročilá analytika",
        "Multi-jazyčnosť (5+ jazykov)",
        "Unlimited revízie",
        "Prioritná e-mailová podpora",
        "12 mesiacov technickej podpory",
      ],
    },
  ],
  technicalDetails: {
    Frontend: ["Next.js 14", "React 18", "TypeScript", "Tailwind CSS", "Framer Motion"],
    Backend: ["NestJS", "Node.js", "Express"],
    Database: ["PostgreSQL", "Redis Cache"],
    Hosting: ["Vercel", "AWS", "Docker"],
    Performance: ["Lighthouse > 90", "Core Web Vitals Optimized", "CDN Integration"],
  },
  timeline: "3-4 týždne",
  support: "24/7 technická podpora",
};
