import type { CatalogProduct } from "../types";

// Pentest pricing tiers completed from brief pattern — adjust amounts if needed.
export const penetrationTesting: CatalogProduct = {
  id: "sec-pentest-001",
  name: "Penetračné Testovanie",
  slug: "penetracne-testovanie",
  category: "security",
  shortDescription: "Komplexný bezpečnostný audit vašich systémov",
  features: [
    "Testovanie webových aplikácií",
    "Bezpečnostný audit siete",
    "Recenzia konfigurácií servera",
    "SQL Injection testovanie",
    "XSS zraniteľnosť",
    "CSRF ochrana",
    "Authentication bypass",
    "Kontrola autorizácie",
    "Detailný bezpečnostný report",
    "Návrhy nápravy",
  ],
  owasp: "OWASP Top 10 Testing",
  deliverables: [
    "Executive Summary",
    "Technický report (50+ strán)",
    "Databáza zraniteľností",
    "Risk assessment matica",
    "Plán nápravy",
    "Re-test po oprávach",
  ],
  pricing: [
    {
      id: "basic",
      name: "Základný Audit",
      price: 1500,
      currency: "EUR",
      billingPeriod: "one-time",
      description: "Pre menšie weby a interné nástroje",
      features: [
        "1 webová aplikácia",
        "OWASP Top 10 scan",
        "Základný report",
        "Email konzultácia",
      ],
    },
    {
      id: "professional",
      name: "Profesionálny Audit",
      price: 3500,
      currency: "EUR",
      billingPeriod: "one-time",
      isPopular: true,
      description: "Pre produkčné systémy s citlivými dátami",
      features: [
        "Web + API testovanie",
        "Autentifikácia a autorizácia",
        "Detailný technický report",
        "Risk assessment matica",
        "1 re-test po opravách",
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise Audit",
      price: 7500,
      currency: "EUR",
      billingPeriod: "one-time",
      description: "Komplexný audit infraštruktúry",
      features: [
        "Web, API, sieť, server",
        "Dedikovaný pentester",
        "Executive + technický report",
        "Plán nápravy s prioritami",
        "2 re-testy po opravách",
        "Prioritná podpora",
      ],
    },
  ],
};
